apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: dotnet311024githubjenkins 
  janus-idp.io/tekton: dotnet311024githubjenkins
  backstage.io/kubernetes-id: dotnet311024githubjenkins
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dotnet311024githubjenkins
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  